# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set OTA minor version
      run: |
        if git diff --name-only HEAD^ HEAD | grep -qE '^ios/|^android/'; then
          echo "Relevant files have changed. Adding 'tagpr:minor' label."
          gh pr edit ${{ github.event.pull_request.number }} --add-label "tagpr:minor"
        else
          echo "No relevant changes detected. Skipping label addition."
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}