# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v4
    # - name: Modified files
    #   run: |
    #     echo "=============== list modified files ==============="
    #     git diff --name-only origin/main
    # - uses: Songmu/tagpr@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changes
      run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}