# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Songmu/tagpr@v1
      id: tagpr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check native file changes and set ota minor label
      id: check_native_file_changes
      run: |
        if ! git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -qE 'ios|android'; then
          echo "No relevant files changed. Exiting job."
          exit 0
        fi
        echo "relevant_files_changed=true" >> $GITHUB_OUTPUT

        if [ ! -z "${{ steps.tagpr.outputs.pull_request_number }}" ]; then
          PR_NUMBER="${{ steps.tagpr.outputs.pull_request_number }}"
        else
          PR_NUMBER=$(gh pr list --base main --label tagpr --json number --jq '.[0].number')
        fi

        if [ ! -z "$PR_NUMBER" ]; then
          gh pr edit $PR_NUMBER --add-label "tagpr:minor"
          echo "Added tagpr:minor label to PR #$PR_NUMBER"
        else
          echo "No suitable PR found to add the tagpr:minor label"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Rerun tagpr if relevant files changed
      if: ${{ steps.check_native_file_changes.outputs.relevant_files_changed == 'true' }}
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}