# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check native file changes
      id: check_native_file_changes
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -qE 'ios|android'; then
          echo "relevant_files_changed=true" >> $GITHUB_OUTPUT
        else
          echo "relevant_files_changed=false" >> $GITHUB_OUTPUT
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v4
    - name: Set minor label
      if: steps.check_native_file_changes.outputs.relevant_files_changed == 'true'
      run: |
        gh pr edit ${{ steps.tagpr.outputs.pull_request.number }} --add-label "tagpr:minor"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}