# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set OTA major version
      run: |
        if git diff --name-only origin/main | grep -qE 'ios|android|package.json'; then
          echo "Relevant files have changed. Adding 'tagpr:major' label."
          gh pr edit ${{steps.tagpr.outputs.pull_request.number}} --add-label "tagpr:major"
        else
          echo "No relevant changes detected. Skipping label addition."
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}