# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]
  pull_request:
    types: 
      - labeled
    paths:
      - 'CHANGELOG.md'
jobs:
  tagpr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.AMEGO_RELEASES_APP_ID }}
        private-key: ${{ secrets.AMEGO_RELEASES_APP_TOKEN }}
    - uses: actions/checkout@v4
    - uses: Songmu/tagpr@v1
      id: tagpr
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check native file changes and set ota minor label
      id: check_native_file_changes
      run: |
        if ! git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -qE 'ios|android'; then
          echo "No relevant files changed. Exiting job."
          exit 0
        fi

        if [ ! -z "${{ steps.tagpr.outputs.pull_request.number }}" ]; then
          PR_NUMBER="${{ steps.tagpr.outputs.pull_request.number }}"
        else
          PR_NUMBER=$(gh pr list --base main --label tagpr --state open --json number --jq '.[0].number')
        fi

        if [ -z "$PR_NUMBER" ]; then
          echo "No PR number found. Exiting job."
          exit 0
        fi

        # # Bump minor version in package.json
        # current_version=$(jq -r '.version' package.json)
        # new_version=$(echo $current_version | awk -F. -v OFS=. '{$2+=1; $3=0; print}')
        # jq --arg new_version "$new_version" '.version = $new_version' package.json > tmp.$$.json && mv tmp.$$.json package.json
        # echo "Bumped version from $current_version to $new_version in package.json"]

        # git add package.json
        # git commit -m "Bump version for ota update"
        # git push

        gh pr edit $PR_NUMBER --add-label "tagpr:minor"
        echo "Added native-change label to PR #$PR_NUMBER"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}